const data = [
  {
    id: "1",
    lien: "https://youtu.be/rZYycIiJwZc",
    titre: "Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "théâtre",
  },
  {
    id: "2",
    lien: "https://youtu.be/WyKhoLLdf5w",
    titre: "Blue plasma",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
  {
    id: "3",
    lien: "https://youtu.be/SDubbiZE6VI",
    titre: "Blue Sci-Fi",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "4",
    lien: "https://youtu.be/xgIxdEFI7u0",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "5",
    lien: "https://youtu.be/xgIxdEFI7u0",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
  {
    id: "6",
    lien: "https://youtu.be/rZYycIiJwZc",
    titre: "Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
  {
    id: "7",
    lien: "https://youtu.be/WyKhoLLdf5w",
    titre: "Blue plasma",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },

  {
    id: "8",
    lien: "https://youtu.be/SDubbiZE6VI",
    titre: "Blue Sci-Fi",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "9",
    lien: "https://youtu.be/xgIxdEFI7u0",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "10",
    lien: "https://youtu.be/xgIxdEFI7u0",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
];

export default data;
