const data = [
  {
    id: "1",
    lien: "assets/videos/video1.mp4",
    titre: "Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "théâtre",
  },
  {
    id: "2",
    lien: "assets/videos/video2.mp4",
    titre: "Blue plasma",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
  {
    id: "3",
    lien: "assets/videos/video1.mp4",
    titre: "Blue Sci-Fi",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "4",
    lien: "assets/videos/video2.mp4",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "5",
    lien: "assets/videos/video3.mp4",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
  {
    id: "6",
    lien: "assets/videos/video4.mp4",
    titre: "Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
  {
    id: "7",
    lien: "assets/videos/video1.mp4",
    titre: "Blue plasma",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },

  {
    id: "8",
    lien: "assets/videos/video2.mp4",
    titre: "Blue Sci-Fi",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "9",
    lien: "assets/videos/video3.mp4",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "comédie",
  },
  {
    id: "10",
    lien: "assets/videos/video4.mp4",
    titre: "Seamless Blue Circles",
    categorie_id: "",
    description_text: "lorem ipsum dolor sit amet, consectetur adipiscing",
    date_publication: "",
    videos_id: "",
    category: "action",
  },
];

export default data;
